// <auto-generated />
using System;
using DataAccessKatmani.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessKatmani.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250310220050_a1")]
    partial class a1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityKatmani.Entitys.FavoriListesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("FavoriListeleri");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.KaraListe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("KaraListelesi");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.Uretici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ureticiler");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanUye")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UreticiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("UreticiId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.UrunIcerik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("UrunIcerikleri");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UyelikTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.FavoriListesi", b =>
                {
                    b.HasOne("EntityKatmani.Entitys.Uye", null)
                        .WithMany("UyeFavoriListesi")
                        .HasForeignKey("UyeId");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.KaraListe", b =>
                {
                    b.HasOne("EntityKatmani.Entitys.Uye", null)
                        .WithMany("UyeKaraListe")
                        .HasForeignKey("UyeId");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.Urun", b =>
                {
                    b.HasOne("EntityKatmani.Entitys.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityKatmani.Entitys.Uretici", "Uretici")
                        .WithMany("Urunler")
                        .HasForeignKey("UreticiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Uretici");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.UrunIcerik", b =>
                {
                    b.HasOne("EntityKatmani.Entitys.Urun", "Urun")
                        .WithMany("UrunIcerikler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.Uretici", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.Urun", b =>
                {
                    b.Navigation("UrunIcerikler");
                });

            modelBuilder.Entity("EntityKatmani.Entitys.Uye", b =>
                {
                    b.Navigation("UyeFavoriListesi");

                    b.Navigation("UyeKaraListe");
                });
#pragma warning restore 612, 618
        }
    }
}
